## following the guide provided by DigitalOcean
## https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04

- apt:
    name: "{{ item }}"
    cache_valid_time: 3600
  with_items:
  - default-jdk

- name: create tomcat user
  user:
    name: "{{ tomcat_user }}"
    shell: /bin/false
    home: "{{ tomcat_home }}"

- name: get Tomcat
  unarchive:
    dest: "{{ tomcat_home }}"
    src: http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    owner: root
    group: "{{ tomcat_user }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1


- name: set permissions on conf/
  file:
    path: "{{ tomcat_home }}/conf"
    recurse: yes
    mode: 0755
    group: "{{ tomcat_user }}"
    owner: root

- name: set permissions
  file:
    path: "{{ tomcat_home }}/{{ item }}"
    recurse: yes
    owner: "{{ tomcat_user }}"
  with_items:
    - webapps
    - work
    - temp
    - logs

- name: create systemd service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: reload
  systemd:
    daemon_reload: yes
